[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
command = "tuigreet --time --remember --remember-user-session --cmd /usr/bin/zsh"
user = "greeter"

# Auto-login for live ISO - boots directly to koompi user
[initial_session]
command = "/usr/bin/zsh -l"
user = "koompi"
