[package]
name = "koompi-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
smithay = { workspace = true }
iced = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
